name: CI - Testes e Qualidade

on:
  pull_request:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          pytest || echo "Nenhum teste configurado ainda"

      - name: Analisar qualidade com flake8
        run: |
          pip install flake8
          flake8 . || echo "Avisos de estilo ignorados por enquanto"

